### ISSUE TITLE
Plugin parserfunctions - new escape request

### ISSUE THREAD

**Issue by nerun** [nerun/dokuwiki-plugin-parserfunctions#1]
Received by e-mail:

> ## Sangara Sorama wrote:
>
> Hello,
>
>I am working on a wiki project with a team, and we want to use your plugin parserfunction for its switch option which is amazing to us!
>
>But we would like to use the characters { and } in the escape, which are not included in your code. Could you please add them to your code?
>
>According to [freeformatter.com](http://freeformatter.com/), it should be :
> - "&&num;123;"  => "{",
> - "&&num;125;"  => "}", 
>
>I do not know how to make a Pull Request and do it myself, hence this email, I am sorry for this.
>
>Thank you in advance, have a nice day !

**Comment by nerun** [comment]
In true, must be:

- `"&&num;123;" => "{",`
- `"&&num;125;" => "}"`

**Comment by SangaraSorama** [comment]
Thank you very much for your quick response!!
Yes, if you can add these 2 lines on the lines 310 and 311 of syntax.php it would be amazing !
I really don't know how to use Git, so I can not make a Pull Request, I'm so sorry to basically ask you to do everything.

**Comment by nerun** [comment]
You are welcome.

Closed as done by commit 08fabb9.
